use clap::{Parser, Subcommand};
use std::path::PathBuf;

#[derive(Parser)]
#[command(name = "gpu-compressor")]
#[command(version = "0.1.0")]
#[command(about = "GPU-accelerated file compression using nvCOMP")]
pub(crate) struct Args {
    #[command(subcommand)]
    pub command: Commands,
}

#[derive(Subcommand)]
pub(crate) enum Commands {
    /// Compress one or more files using the GPU
    ///
    /// Output path is auto-generated if not specified (.nvzs).
    /// When multiple inputs are given and -o is omitted, each output is auto-generated.
    /// When -o is a directory, outputs are placed inside it.
    Compress {
        /// Input file(s) or directory
        #[arg(short, long, num_args = 1..)]
        input: Vec<PathBuf>,
        /// Output path (optional; auto-generated from input name if omitted)
        #[arg(short, long)]
        output: Option<PathBuf>,
        /// Compression algorithm: zstd (default), lzma2
        #[arg(short = 'a', long, default_value = "zstd")]
        algorithm: String,
        /// CUDA device ID
        #[arg(short, long, default_value = "0")]
        device: i32,
        /// Compression level: 0 = fast, 1-2 = custom GPU kernel (zstd), 0-9 = preset (lzma2)
        #[arg(short = 'l', long, default_value = "0")]
        level: u32,
        /// Chunk size for parallel multi-file processing (bytes, default 128 MiB)
        #[arg(long, default_value = "134217728")]
        chunk_size: usize,
        /// LZMA2 dictionary size in MiB (default 128, max limited by available RAM)
        #[arg(long, default_value = "128")]
        dict_size: u32,
    },
    /// Decompress one or more compressed files using the GPU
    ///
    /// Output path is auto-generated by stripping the .nvzs extension if not specified.
    /// When -o is a directory, outputs are placed inside it.
    Decompress {
        /// Input file(s)
        #[arg(short, long, num_args = 1..)]
        input: Vec<PathBuf>,
        /// Output path (optional; auto-generated from input name if omitted)
        #[arg(short, long)]
        output: Option<PathBuf>,
        /// CUDA device ID
        #[arg(short, long, default_value = "0")]
        device: i32,
    },
}
